language: ruby
rvm:
  - ruby-2.2.3
services:
  - postgresql
branches:
  only:
    - master
before_script:
  - psql -c 'create database task_mgr_test' -U postgres
script:
  - RAILS_ENV=test bundle exec rake db:migrate --trace
  - bundle exec rspec spec
